### ISSUE TITLE
Python Bootcamp Material

### ISSUE THREAD

**Issue by jtyoung84** [AllenInstitute/swdb_2022_python_bootcamp#1]
The Python Bootcamp is a two-day crash course on python coding fundamentals. The final deliverable will be in the form of a folder of jupyter notebooks hosted in the [main project repo](https://github.com/AllenInstitute/swdb_2022). Four TA's have been assigned to cover the bootcamp: Koosha, Jon, Praveen, and Daniel. The following tasks will need be completed in order for this backlog item to be considered finished:

**Tasks**

- [x] Get answer to questions:
    - [x] Is each TA responsible for teaching all the material or just a small portion?
        Each TA should be familiar with all the material, but will only be responsible for lecturing on one or two notebooks.
    - [x] Should we include [seaborn](https://seaborn.pydata.org)?
    - [x] How much git management should we cover? We're moving the git presentation into the main course, so this section can be removed from the bootcamp.
- [x] Create a private fork of the main repo to develop the course material. We can open a Pull Request for review when the course material is ready.
- [ ] Create a rough syllabus of the course. The syllabus should contain: time and location, a brief intro describing the course, and an estimated outline for when each topic will be covered.
- [x] Modify the [course material](https://github.com/AllenInstitute/swdb_2022_python_bootcamp/tree/main/PythonBootcamp) based on feedback. We can divvy up the workload such that each TA is mainly responsible for maintaining a handful of related notebooks. Each TA will be responsible for covering the following sections (updated as of 2022-08-16):
    - [x] (Michael) 00_Introduction.ipynb (Sat.)
    - [x] (Michael) 01_Basic_Python_I_Object_and_Data_Structures.ipynb (Sat.)
    - [x] (Michael) 02_Basic_Python_II_Control_Flow_and_Functions.ipynb (Sat.)
    - [x] (Koosha) 03_Intro_To_Scientific_Computing.ipynb (Sat.)
    - [x] (Koosha) 04_Introduction_To_Numpy.ipynb (Sat.)
    - [ ] (Luke?) 05_Introduction_To_Matplotlib.ipynb (Sat.)
    - [x] (Jon) 06_Custom_Modules.ipynb (Sat.)
    - [x] (Jon) 07_Conda_Environments.ipynb (Sat.)
    - [x] (Jon) 08_Development_Tools.ipynb (Sat.)
    - [x] (Clark) 09_Introduction_To_Pandas.ipynb (Sun.)
